
# Before updating this file in any of the Austin Transportation repos, 
# try to run it through a YAML linter like http://www.yamllint.com/ first. 
# This will help identify any syntax errors in YAML that would prevent labels 
# from being updated automatically.

# Note that adding this file to a repo will overwrite all its existing labels.

--- 
labels: 
  - 
    color: 5F7D8C
    description: ""
    name: Duplicate
  - 
    color: 3E4B9E
    description: ""
    name: Epic
  - 
    color: FF7261
    description: "Severely impacts ATD service delivery"
    name: "Impact: 1-Severe"
  - 
    color: FF9A8E
    description: "Causes a major interruption of ATD service delivery"
    name: "Impact: 2-Major"
  - 
    color: FFCDCA
    description: "Deteriorates ATD service delivery"
    name: "Impact: 3-Minor"
  - 
    color: FFEEED
    description: "Does not affect ATD service delivery"
    name: "Impact: 4-None"
  - 
    color: 3E4B9E
    description: "Contains a project's overview and status in addition to relevant assets, data, and information"
    name: Index
  - 
    color: FF7261
    description: "No point in delivering a solution without this"
    name: "Need: 1-Must Have"
  - 
    color: FF9A8E
    description: "May be painful to leave out, but the solution is still viable"
    name: "Need: 2-Should Have"
  - 
    color: FFCDCA
    description: "Wanted, but affects fewer users or has less impact on business than other features"
    name: "Need: 3-Could Have"
  - 
    color: FFE9E9
    description: "Will not be delivered at this time"
    name: "Need: 4-Won't Have"
  - 
    color: F2FC6D
    description: "Application support"
    name: "Service: Apps"
    oldname: "Team: Apps"
  - 
    color: F2FC6D
    description: "Infrastructure and engineering"
    name: "Service: Dev"
    oldname: "Team: Dev"
  - 
    color: F2FC6D
    description: "Geospatial services"
    name: "Service: Geo"
    oldname: "Team: Geo"
  - 
    color: F2FC6D
    description: "Product and project management"
    name: "Service: PM"
    oldname: "Team: PM"
  - 
    color: 0B3E79
    description: "Something is not right"
    name: "Type: Bug Report"
  - 
    color: 0B3E79
    description: "Presentations, blog posts, etc."
    name: "Type: Communication"
  - 
    color: 0B3E79
    description: "Generating and delivering datasets and reports"
    name: "Type: Data"
  - 
    color: 0B3E79
    description: "User guides, developer documentation, planning documents, etc."
    name: "Type: Documentation"
  - 
    color: 0B3E79
    description: "Request for an improvement to existing functionality in an application"
    name: "Type: Enhancement"
  - 
    color: 0B3E79
    description: "Request for new functionality in an existing application"
    name: "Type: Feature"
  - 
    color: 0B3E79
    description: "Software licenses, user accounts and logins, hardware set up, etc."
    name: "Type: IT Support"
  - 
    color: 0B3E79
    description: "Request for a map"
    name: "Type: Map Request"
  - 
    color: 0B3E79
    description: "Scheduled discussion, work session, etc."
    name: "Type: Meeting"
  - 
    color: 0B3E79
    description: "Request for a new application; user needs cannot be met by an existing application"
    name: "Type: New Application"
  - 
    color: 0B3E79
    description: "Not covered by other issue types"
    name: "Type: Other"
  - 
    color: 0B3E79
    description: "Request for reporting"
    name: "Type: Reports"
  - 
    color: 0B3E79
    description: "Research or discovery work"
    name: "Type: Research"
  - 
    color: 0B3E79
    description: "Testing for usability, security, performance, accessibility, etc."
    name: "Type: Testing"
  - 
    color: 0B3E79
    description: "Request for training"
    name: "Type: Training"
  - 
    color: 5F7D8C
    description: "Work in progress"
    name: "WIP"
  - 
    color: 00BFA5
    description: "Arterial Management Division"
    name: "Workgroup: AMD"
  - 
    color: 00BFA5
    description: "Active Transportation and Street Design"
    name: "Workgroup: ATSD"
  - 
    color: 00BFA5
    description: "Cooridor Program Office"
    name: "Workgroup: CPO"
  - 
    color: 00BFA5
    description: "Communications and Technology Management"
    name: "Workgroup: CTM"
  - 
    color: 00BFA5
    description: "Data and Technology Services"
    name: "Workgroup: DTS"
  - 
    color: 00BFA5
    description: "Finance and Administration"
    name: "Workgroup: Finance"
  - 
    color: 00BFA5
    description: "Human Resources"
    name: "Workgroup: HR"
  - 
    color: 00BFA5
    description: "Office of the Director"
    name: "Workgroup: OOD"
  - 
    color: 00BFA5
    description: "Office of Special Events"
    name: "Workgroup: OSE"
  - 
    color: 00BFA5
    description: ""
    name: "Workgroup: Other"
  - 
    color: 00BFA5
    description: "Parking Enterprise"
    name: "Workgroup: PE"
  - 
    color: 00BFA5
    description: "Public Information Officers"
    name: "Workgroup: PIO"
  - 
    color: 00BFA5
    description: "Public Works Department"
    name: "Workgroup: PWD"
  - 
    color: 00BFA5
    description: "Right of Way Management"
    name: "Workgroup: ROW"
  - 
    color: 00BFA5
    description: "Systems Development Division"
    name: "Workgroup: SDD"
  - 
    color: 00BFA5
    description: "Signs and Markings (and Banners)"
    name: "Workgroup: SMB"
  - 
    color: 00BFA5
    description: "Smart Mobility"
    name: "Workgroup: SM"
  - 
    color: 00BFA5
    description: "Transportation Engineering"
    name: "Workgroup: TE"
  - 
    color: 00BFA5
    description: "Vision Zero Program"
    name: "Workgroup: VZ"
